<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Bimbel;
use App\Models\User;

class DummyBimbelSeeder extends Seeder
{
    public function run(): void
    {
        $adminUser = User::where('role', 'admin')->first() ?? User::first();
        $userId = $adminUser ? $adminUser->id : 1;

        $bimbels = [
            [
                'user_id' => $userId,
                'nama' => 'RuangBelajar Smart',
                'mapel' => 'Matematika, Fisika, Kimia',
                'jenjang' => 'SMA',
                'kota' => 'Jakarta Selatan',
                'alamat' => 'Jl. Kebayoran Baru No. 45, Jakarta Selatan',
                'telepon' => '081234567801',
                'email' => 'info@ruangbelajarsmart.com',
                'website' => 'https://ruangbelajarsmart.com',
                'deskripsi' => 'Bimbel khusus Matematika, Fisika, dan Kimia SMA dengan metode cepat dan pemahaman konsep mendalam untuk persiapan SNBT dan Ujian Sekolah.',
                'harga_mulai' => 450000,
                'jam_operasional' => '08:00 - 17:00 WIB',
                'status' => 'Aktif',
            ],
            [
                'user_id' => $userId,
                'nama' => 'Ganesha Innovation Center',
                'mapel' => 'Fisika, Matematika, Biologi',
                'jenjang' => 'SMA',
                'kota' => 'Bandung',
                'alamat' => 'Jl. Dago No. 112, Bandung',
                'telepon' => '081234567802',
                'email' => 'contact@ganeshainnovation.com',
                'website' => 'https://ganeshainnovation.com',
                'deskripsi' => 'Pengajaran Fisika, Matematika, dan Biologi berbasis eksperimen dan latihan soal intensif oleh alumni ITB bereputasi.',
                'harga_mulai' => 550000,
                'jam_operasional' => '09:00 - 18:00 WIB',
                'status' => 'Aktif',
            ],
            [
                'user_id' => $userId,
                'nama' => 'English Excellence Academy',
                'mapel' => 'Bahasa Inggris, TOEFL, Conversation',
                'jenjang' => 'Umum',
                'kota' => 'Surabaya',
                'alamat' => 'Jl. Raya Darmo No. 88, Surabaya',
                'telepon' => '081234567803',
                'email' => 'admin@englishexcellence.id',
                'website' => 'https://englishexcellence.id',
                'deskripsi' => 'Kursus Bahasa Inggris komprehensif mulai dari Conversation, Business English, hingga TOEFL/IELTS Preparation.',
                'harga_mulai' => 350000,
                'jam_operasional' => '10:00 - 20:00 WIB',
                'status' => 'Aktif',
            ],
            [
                'user_id' => $userId,
                'nama' => 'Bintang Pelajar Mandiri',
                'mapel' => 'IPA, Matematika, Bahasa Indonesia',
                'jenjang' => 'SMP',
                'kota' => 'Bogor',
                'alamat' => 'Jl. Pajajaran No. 23, Bogor',
                'telepon' => '081234567804',
                'email' => 'halo@bintangpelajar.co.id',
                'website' => 'https://bintangpelajar.co.id',
                'deskripsi' => 'Bimbingan belajar Sains terpadu SMP untuk membangun dasar IPA, Matematika, dan Bahasa Indonesia yang kokoh.',
                'harga_mulai' => 400000,
                'jam_operasional' => '13:00 - 19:00 WIB',
                'status' => 'Aktif',
            ],
            [
                'user_id' => $userId,
                'nama' => 'Koding Kids Indonesia',
                'mapel' => 'Informatika, Coding, Game Development',
                'jenjang' => 'SD',
                'kota' => 'Depok',
                'alamat' => 'Jl. Margonda Raya No. 300, Depok',
                'telepon' => '081234567805',
                'email' => 'hello@kodingkids.id',
                'website' => 'https://kodingkids.id',
                'deskripsi' => 'Kursus pemrograman komputer interaktif, coding dasar, dan pembuatan game seru khusus anak-anak tingkat SD.',
                'harga_mulai' => 600000,
                'jam_operasional' => '09:00 - 16:00 WIB',
                'status' => 'Aktif',
            ],
            [
                'user_id' => $userId,
                'nama' => 'Kimia Super Master',
                'mapel' => 'Kimia, Fisika',
                'jenjang' => 'SMA',
                'kota' => 'Semarang',
                'alamat' => 'Jl. Pandanaran No. 70, Semarang',
                'telepon' => '081234567806',
                'email' => 'cs@kimiasuper.com',
                'website' => 'https://kimiasuper.com',
                'deskripsi' => 'Bedah tuntas rumus & reaksi Kimia SMA dengan trik cepat pengerjaan soal ujian.',
                'harga_mulai' => 500000,
                'jam_operasional' => '14:00 - 20:00 WIB',
                'status' => 'Aktif',
            ],
            [
                'user_id' => $userId,
                'nama' => 'Nihongo Gakkou Center',
                'mapel' => 'Bahasa Jepang',
                'jenjang' => 'Umum',
                'kota' => 'Yogyakarta',
                'alamat' => 'Jl. Kaliurang Km 5, Yogyakarta',
                'telepon' => '081234567807',
                'email' => 'info@nihongogakkou.id',
                'website' => 'https://nihongogakkou.id',
                'deskripsi' => 'Belajar Bahasa Jepang langsung dengan Native Speaker & persiapan JLPT N5 hingga N2.',
                'harga_mulai' => 300000,
                'jam_operasional' => '10:00 - 18:00 WIB',
                'status' => 'Aktif',
            ],
            [
                'user_id' => $userId,
                'nama' => 'LesGO Privat Matematika',
                'mapel' => 'Matematika',
                'jenjang' => 'SMP',
                'kota' => 'Malang',
                'alamat' => 'Jl. Soekarno Hatta No. 15, Malang',
                'telepon' => '081234567808',
                'email' => 'support@lesgoprivat.com',
                'website' => 'https://lesgoprivat.com',
                'deskripsi' => 'Bimbingan Matematika SMP 1-on-1 dengan jadwal fleksibel dan pendekatan personal sesuai kebutuhan siswa.',
                'harga_mulai' => 380000,
                'jam_operasional' => '08:00 - 20:00 WIB',
                'status' => 'Aktif',
            ],
            [
                'user_id' => $userId,
                'nama' => 'Akademi Biologi Nusantara',
                'mapel' => 'Biologi',
                'jenjang' => 'SMA',
                'kota' => 'Surakarta',
                'alamat' => 'Jl. Slamet Riyadi No. 210, Surakarta',
                'telepon' => '081234567809',
                'email' => 'admin@biologinusantara.com',
                'website' => 'https://biologinusantara.com',
                'deskripsi' => 'Pemahaman materi Biologi visual & mendalam untuk persiapan Ujian Nasional dan Seleksi Kedokteran.',
                'harga_mulai' => 420000,
                'jam_operasional' => '13:00 - 18:00 WIB',
                'status' => 'Aktif',
            ],
            [
                'user_id' => $userId,
                'nama' => 'Mandarin Champion Club',
                'mapel' => 'Bahasa Mandarin',
                'jenjang' => 'SD',
                'kota' => 'Medan',
                'alamat' => 'Jl. Asia No. 99, Medan',
                'telepon' => '081234567810',
                'email' => 'mandarin@champion.co.id',
                'website' => 'https://mandarinchampion.co.id',
                'deskripsi' => 'Kursus Bahasa Mandarin menyenangkan untuk anak SD dengan lagu, permainan, dan latihan HSK 1-3.',
                'harga_mulai' => 480000,
                'jam_operasional' => '14:00 - 19:00 WIB',
                'status' => 'Aktif',
            ],
            [
                'user_id' => $userId,
                'nama' => 'Super Intensif UTBK SBMPTN',
                'mapel' => 'TPS & TKA',
                'jenjang' => 'SMA',
                'kota' => 'Jakarta Pusat',
                'alamat' => 'Jl. Salemba Raya No. 12, Jakarta Pusat',
                'telepon' => '081234567811',
                'email' => 'utbk@superintensif.com',
                'website' => 'https://superintensif.com',
                'deskripsi' => 'Program drill soal TPS, Penalaran Matematika, dan Literasi Bahasa untuk tembus PTN Favorit.',
                'harga_mulai' => 750000,
                'jam_operasional' => '08:00 - 18:00 WIB',
                'status' => 'Aktif',
            ],
            [
                'user_id' => $userId,
                'nama' => 'Bilingual Toddler & Kids',
                'mapel' => 'Bahasa Inggris',
                'jenjang' => 'TK',
                'kota' => 'Tangerang Selatan',
                'alamat' => 'Jl. BSD Grand Boulevard No. 5, Tangerang Selatan',
                'telepon' => '081234567812',
                'email' => 'info@bilingualkids.id',
                'website' => 'https://bilingualkids.id',
                'deskripsi' => 'Metode Montessori & Phonics untuk mengenalkan Bahasa Inggris usia dini secara alami dan menyenangkan.',
                'harga_mulai' => 650000,
                'jam_operasional' => '09:00 - 15:00 WIB',
                'status' => 'Aktif',
            ],
            [
                'user_id' => $userId,
                'nama' => 'Informatika & Web Design Pro',
                'mapel' => 'Informatika',
                'jenjang' => 'Mahasiswa',
                'kota' => 'Bekasi',
                'alamat' => 'Jl. Ahmad Yani No. 50, Bekasi',
                'telepon' => '081234567813',
                'email' => 'dev@webdesignpro.id',
                'website' => 'https://webdesignpro.id',
                'deskripsi' => 'Bootcamp Fullstack Web Development (Laravel & React) dari nol hingga siap kerja di industri IT.',
                'harga_mulai' => 850000,
                'jam_operasional' => '10:00 - 21:00 WIB',
                'status' => 'Aktif',
            ],
            [
                'user_id' => $userId,
                'nama' => 'Rumah Belajar IPS Terpadu',
                'mapel' => 'IPS',
                'jenjang' => 'SMP',
                'kota' => 'Palembang',
                'alamat' => 'Jl. Veteran No. 34, Palembang',
                'telepon' => '081234567814',
                'email' => 'ips@rumahbelajar.com',
                'website' => 'https://rumahbelajarips.com',
                'deskripsi' => 'Bimbel Geografi, Sejarah, Ekonomi, dan Sosiologi SMP secara terpadu dengan peta konsep interaktif.',
                'harga_mulai' => 320000,
                'jam_operasional' => '13:00 - 18:00 WIB',
                'status' => 'Aktif',
            ],
            [
                'user_id' => $userId,
                'nama' => 'Mastering TOEFL & IELTS Pro',
                'mapel' => 'Bahasa Inggris',
                'jenjang' => 'Mahasiswa',
                'kota' => 'Makassar',
                'alamat' => 'Jl. Ujung Pandang No. 77, Makassar',
                'telepon' => '081234567815',
                'email' => 'toefl@masteringpro.com',
                'website' => 'https://masteringpro.com',
                'deskripsi' => 'Kelas intensif persiapan beasiswa luar negeri & target skor TOEFL iBT 100+ / IELTS 7.0+.',
                'harga_mulai' => 950000,
                'jam_operasional' => '09:00 - 20:00 WIB',
                'status' => 'Aktif',
            ],
        ];

        foreach ($bimbels as $data) {
            Bimbel::create($data);
        }
    }
}
